# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-25 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_sinaauthuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinaauthuser',
            old_name='openid',
            new_name='access_token',
        ),
    ]
