# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-12 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': '广告类别', 'verbose_name_plural': '广告类别'},
        ),
    ]
